const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const Cat_LeaveDayTypeSchema = new Schema({
  ID: { type: Schema.Types.String },
  LeaveDayTypeName: { type: Schema.Types.String },
  Code: { type: Schema.Types.String },
  CodeStatistic: { type: Schema.Types.String },
  PaidRate: { type: Schema.Types.String },
  SalaryType: { type: Schema.Types.String },
  Penalty: { type: Schema.Types.String },
  IsWorkDay: { type: Schema.Types.String },
  IsAnnualLeave: { type: Schema.Types.String },
  MaxPerTimes: { type: Schema.Types.String },
  MaxPerYear: { type: Schema.Types.String },
  OrgStructureID: { type: Schema.Types.String },
  IsTimeOffInLieu: { type: Schema.Types.String },
  ServerUpdate: { type: Schema.Types.String },
  ServerCreate: { type: Schema.Types.String },
  UserUpdate: { type: Schema.Types.String },
  UserCreate: { type: Schema.Types.String },
  DateCreate: { type: Schema.Types.String },
  DateUpdate: { type: Schema.Types.String },
  UserLockID: { type: Schema.Types.String },
  DateLock: { type: Schema.Types.String },
  IsDelete: { type: Schema.Types.String },
  IPCreate: { type: Schema.Types.String },
  IPUpdate: { type: Schema.Types.String },
  SocialRate: { type: Schema.Types.String },
  IsSystem: { type: Schema.Types.String },
  MaxLeaveDay: { type: Schema.Types.String },
  MaxLeaveDayType: { type: Schema.Types.String },
  InsuranceType: { type: Schema.Types.String },
  Formula: { type: Schema.Types.String },
  IsTimeOffMakeUp: { type: Schema.Types.String },
  IsLoadRelatives: { type: Schema.Types.String },
  OvertimeID: { type: Schema.Types.String },
  SymbolID: { type: Schema.Types.String },
  Order: { type: Schema.Types.String },
  Notes: { type: Schema.Types.String },
  MissInOutReasonID: { type: Schema.Types.String },
  NotSelectedInPortal: { type: Schema.Types.String },
  CodeLeaveDayDepend: { type: Schema.Types.String },
  MedicalDocument: { type: Schema.Types.String },
  IsSick: { type: Schema.Types.String },
  IsInsuranceLeave: { type: Schema.Types.String },
  DurationType: { type: Schema.Types.String },
  TypeHalfShift: { type: Schema.Types.String },
  UnitHour: { type: Schema.Types.String },
  MaxRequestPerMonth: { type: Schema.Types.String },
  MaxRequestPerYear: { type: Schema.Types.String },
  MaxRequestPerLifeTime: { type: Schema.Types.String },
  IsMenses: { type: Schema.Types.String },
  SortID: { type: Schema.Types.String },
  IsAdditonalLeave: { type: Schema.Types.String },
  DefaultLeaveDay: { type: Schema.Types.String },
  IsProbationNotLeaveDay: { type: Schema.Types.String },
  DefaultLeaveMonth: { type: Schema.Types.String },
  FileAttach: { type: Schema.Types.String },
  Proiority: { type: Schema.Types.String },
  IsMeal: { type: Schema.Types.String },
  IsNoShift: { type: Schema.Types.String },
  ListRegisterHours: { type: Schema.Types.String },
  IsPregnantLeave: { type: Schema.Types.String },
  MaxUnitHour: { type: Schema.Types.String },
  MaxPerMonth: { type: Schema.Types.String },
  IsBusinessTravel: { type: Schema.Types.String },
  ConditionRegisteredFormula: { type: Schema.Types.String },
  TemplateSendMailID: { type: Schema.Types.String },
});

const Cat_LeaveDayTypeModel = mongoose.model(
  "Cat_LeaveDayType",
  Cat_LeaveDayTypeSchema,
);

module.exports = Cat_LeaveDayTypeModel;
