const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const Cat_ContractTypeSchema = new Schema({
  ID: { type: Schema.Types.String },
  ContractTypeName: { type: Schema.Types.String },
  Type: { type: Schema.Types.String },
  UnitTime: { type: Schema.Types.String },
  ValueTime: { type: Schema.Types.String },
  ReportMappingID: { type: Schema.Types.String },
  ServerUpdate: { type: Schema.Types.String },
  ServerCreate: { type: Schema.Types.String },
  UserUpdate: { type: Schema.Types.String },
  UserCreate: { type: Schema.Types.String },
  DateCreate: { type: Schema.Types.String },
  DateUpdate: { type: Schema.Types.String },
  UserLockID: { type: Schema.Types.String },
  DateLock: { type: Schema.Types.String },
  IsDelete: { type: Schema.Types.String },
  IPCreate: { type: Schema.Types.String },
  IPUpdate: { type: Schema.Types.String },
  Code: { type: Schema.Types.String },
  Description: { type: Schema.Types.String },
  ExportID: { type: Schema.Types.String },
  ExpiryContractLoop: { type: Schema.Types.String },
  DayInMonthLoop1: { type: Schema.Types.String },
  DayInMonthLoop2: { type: Schema.Types.String },
  DayInMonthLoop3: { type: Schema.Types.String },
  ExpiryContractDayByDay: { type: Schema.Types.String },
  EmailToList: { type: Schema.Types.String },
  EmailOther: { type: Schema.Types.String },
  Formula: { type: Schema.Types.String },
  NoneEndContract: { type: Schema.Types.String },
  NoneTypeInsuarance: { type: Schema.Types.String },
  IsSocialInsurance: { type: Schema.Types.String },
  IsHealthInsurance: { type: Schema.Types.String },
  IsUnEmployInsurance: { type: Schema.Types.String },
  TypeForNext: { type: Schema.Types.String },
  AppendixTypeNextID: { type: Schema.Types.String },
  OrderNumber: { type: Schema.Types.String },
  SortID: { type: Schema.Types.String },
  RequestDateQuitDays: { type: Schema.Types.String },
  IsGenerateRequestDate: { type: Schema.Types.String },
  NameInLaw: { type: Schema.Types.String },
  ContractNextID: { type: Schema.Types.String },
  IsStopOldContract: { type: Schema.Types.String },
  IsMultiCreate: { type: Schema.Types.String },
  PositionListCode: { type: Schema.Types.String },
  EmployeeTypeListCode: { type: Schema.Types.String },
  NationalityGroupListCode: { type: Schema.Types.String },
  JobTitleListCode: { type: Schema.Types.String },
  AppendixContractTypeID: { type: Schema.Types.String },
  NumberDayQuitJob: { type: Schema.Types.String },
  FormulaDateSign: { type: Schema.Types.String },
});

const Cat_ContractTypeModel = mongoose.model(
  "Cat_ContractType",
  Cat_ContractTypeSchema,
);

module.exports = Cat_ContractTypeModel;
